version: 2
updates:
  - package-ecosystem: composer
    directory: "/tools/phpstan"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
